name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Jinja2
      - name: Run tests
        run: |
          python risk_service.py &
          sleep 5
          python - <<'PY'
import urllib.request, json, time, sys
url = 'http://localhost:8001/api/risks'
for i in range(5):
    try:
        with urllib.request.urlopen(url) as f:
            data=json.load(f)
        if 'totals' in data and 'Polly' in data['totals'] and 'Lisa' in data['totals']:
            print('Test passed')
            break
    except Exception as e:
        print('Waiting for server...', e)
        time.sleep(2)
else:
    sys.exit('Server not responding or invalid data')
PY
      - name: Build Docker image
        run: |
          docker build -t riskanalysisfunapp:latest .
